on: workflow_dispatch

jobs:
  gogo:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.Secret1 }}
      run: |
        echo "$SUPER_SECRET"
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.user }}
        key: ${{ secrets.key }}
        script: ls
        debug: true
